name: blogify_flutter_main
description: "Blogify - A Blogs and Articles mobile Flutter app"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.8.0
  auto_route: ^9.3.0+1
  provider: ^6.1.2
  intl: ^0.20.2
  flutter_card_swiper: ^7.2.0
  collection: ^1.19.1
  get_it: ^9.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.2.1
  share_plus: ^12.0.2
  cross_file: ^0.3.5+2
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/mocks/

  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro-Regular.ttf
        - asset: assets/fonts/SF-Pro-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Thin.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Light.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Medium.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Semibold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Bold.otf
          weight: 800
